- name: Build project
        run: npm run build
        env:
          AIzaSyAUV29MOEVbaewdBElyZ5POfv6bM9ijKOo
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
